---
- hosts: all
  gather_facts: yes
  become: true
  become_method: dzdo
  become_user: root
  tasks:
  - name: Gathering basic facts
    shell: "{{item}}"
    with_items:
      #- "df -hT  /var/ossec; ps -aef | grep -i ossec"
      - "/usr/sbin/dmidecode | grep -i product"
      #- "uname -a"
    register: output

  - debug:
      msg: "{{ output.results[0].stdout }}"
      #var: "output.results[0].stdout_lines"
