---
# ansible-playbook -i inventory httpd.yml
- hosts: all
  gather_facts: no
  remote_user: ec2-user
  become: true
  become_method: sudo
  become_user: root

  tasks: 
  - name: install httpd package
    yum:
      name: httpd
      state: absent

