---
#ansible-playbook instances_info.yml | grep -i msg
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: instances info
    ec2_instance_info:
      #instance_ids:
      #        #- i-0600a10affdd96266
      filters:
        availability-zone: [ "ap-south-1a", "ap-south-1b", "ap-south-1c" ]
    register: ec2

  - debug:
      msg: "{{ item.instance_id }} ansible_host={{ item.public_ip_address }} ansible_user=ec2-user ansible_ssh_private_key_file=./{{ item.key_name }}"  
    with_items: "{{ ec2.instances }}"
