---
- name: configuring zabbix repo
  yum:
    name: ["https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm", "http://mirror.centos.org/centos/8.0.1905/AppStream/x86_64/os/Packages/libssh2-1.8.0-8.module_el8.0.0+189+f9babebb.1.x86_64.rpm"]
    state: present

- name: installing zabbix packages
  yum:
    name: ['zabbix-server-mysql', 'zabbix-web-mysql', 'zabbix-agent', 'python3-PyMySQL']
    state: present

- name: Install database
  yum:
    name: mariadb-server
    state: present
    
- name: Start Database
  service:
    name: mariadb
    state: started
    enabled: true

# https://stackoverflow.com/questions/25136498/ansible-answers-to-mysql-secure-installation -> mysql_secure_installation

- name: "MySQL | Create database"
  mysql_db:
    name: zabbix
    state: present
    encoding: utf8
    collation: utf8_bin
    login_host: localhost
    login_user: root

- name: "MySQL | Create database user"
  mysql_user:
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL'
    host: localhost
    state: present
