apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        args:
          - "--default-authentication-plugin=mysql_native_password"
        env:
          - name: "MYSQL_USER"
            value: "mysql"
          - name: "MYSQL_PASSWORD"
            value: "mysql"
          - name: "MYSQL_DATABASE"
            value: "sample"
          - name: "MYSQL_ROOT_PASSWORD"
            value: "redhat"
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
