apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysql-pv
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes: 
    - ReadWriteMany
  nfs:
    server: 192.168.56.100
    path: "/srv/nfs/mysql"
